### ISSUE TITLE
Throws an exception while rendering webChat

### ISSUE THREAD

**Issue by thirumaran007** [MicrosoftDocs/bot-docs#1475]
Throws an exception while rendering webChat  like below 
https://********.net/.bot/v3/directline/conversations/*****?watermark= 404 (Not Found)
anyone facing this kind of issue ?

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 1e3a6ed6-7d29-d82e-c86f-8f405ab12fe3
* Version Independent ID: 6a4ba6ea-51df-929f-e307-38c4a1f9b889
* Content: [Use WebChat with the direct line app service extension - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-service-channel-directline-extension-webchat-client?view=azure-bot-service-4.0#feedback)
* Content Source: [articles/bot-service-channel-directline-extension-webchat-client.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-service-channel-directline-extension-webchat-client.md)
* Service: **bot-service**
* GitHub Login: @Kaiqb
* Microsoft Alias: **kamrani**

**Comment by thirumaran007** [comment]
Above exception throws when we use  **var dl = window.WebChat.createDirectLine({** , but when we use **var dl = new DirectLine.DirectLine({**  it shows like below 
![image](https://user-images.githubusercontent.com/4000745/70654913-41b57480-1c25-11ea-8e9c-055d7ba2dc79.png)

**Comment by stevkan** [comment]
@thirumaran007, I've successfully repro'd the issue arriving at the same results. I reached out to one of the devs working on this product and will let update when I know more.

**Comment by stevkan** [comment]
@thirumaran007, thank you for your patience. I am still working with the dev on this. Again, I will send an update when I know more.

**Comment by DDEfromOR** [comment]
Try changing the argument passed in to the DirectLine creation from 'webSocket: true' to 'streamingWebSocket: true'. 

There's an updated version of DirectLine.js coming out soon that will bring with it an update of this doc and a less painful adoption path.

**Comment by stevkan** [comment]
@DDEfromOR, I tried passing 'streamingWebSocket: true' in to no effect. One thing I noticed is my directLine.js file was somehow overwritten with entirely different code which was producing a different error for me. I have since resolved by re-copying the file's code from GitHub.

Interestingly, I can no longer repro the customer's issue. Instead, if I append '.catach( err => console.log( err ) )` to the scripts function call, I now get this error: "DirectLine.DirecteLine is not a constructor".

**Comment by DDEfromOR** [comment]
@stevkan I'm using the HTML below in conjunction with the **subject to change and not yet released** code on [this branch.](https://github.com/microsoft/BotFramework-DirectLineJS/tree/ckk/protocoljs)

In the not too distant future code very similar to what's currently on that branch will find its way into the production version of the Directline.js script used by WebChat. Hopefully this unblocks developers for the time being.

```
<!DOCTYPE html>
<html lang="en-US">
<head>
    <title>Direct Line Streaming Sample</title>
    <script src=".\directline.js"></script>
    <script src="https://cdn.botframework.com/botframework-webchat/master/webchat.js"></script>
    <style>
        html, body {
            height: 100%
        }
        body {
            margin: 0
        }
        #webchat > * {
            height: 100%;
            width: 100%;
        }
    </style>
</head>

<body>
    <div id="webchat" role="main"></div>
    <script>
        const activityMiddleware = () => next => card => {
            if (card.activity.type === 'trace') {
                // Return false means, don't render the trace activities
                return () => false;
            } else {
                return children => next(card)(children);
            }
        };
        var dl = new DirectLine.DirectLine({
            secret: '<Token Goes Here>',
            domain: 'https://<BotID Goes Here>.azurewebsites.net/.bot/v3/directline',
            streamingWebSocket: true,
            conversationId: '<ConversationID Goes here>'
        });
        window.WebChat.renderWebChat({
            activityMiddleware,
            directLine: dl
        }, document.getElementById('webchat'));
    </script>
</body>
</html>
```

**Comment by stevkan** [comment]
@DDEfromOR, I just compiled and tried using the non-production version you suggested above and am getting the following. Are you able to run successfully? Thoughts on the below?

![image](https://user-images.githubusercontent.com/18403946/72769640-4835f500-3bb0-11ea-9434-ecc229e40f91.png)

The above error points to this code, line 6636:
`var _interopRequireDefault = require("@babel/runtime/helpers/interopRequireDefault");`

**Comment by thirumaran007** [comment]
"DirectLine"  of undefined, issue still exist when we use older version of chrome browser( V 40.*, V56.* ). seems  latest version of chrome its just working fine.

**Comment by DDEfromOR** [comment]
@stevkan I'll need to call in @ckkMicrosoft for help debugging the directline.js custom build, but we may just have to wait for the release.

**Comment by stevkan** [comment]
Have connected with CK to try and get the DirectLine.DirectLine() instance to work. However, despite trying different setups, the direct line instance continues to have issues being recognized. CK is also looking at related issues around bot creation on ABS with regards to DL ASE.

**Comment by stevkan** [comment]
Closing as customer has a working version. Kept open due to errors I was receiving (including the above). Utilized a non-published version of directline.js from CK. Also included 'streamingWebSocket: true', as noted by Daniel in the above. Works as expected, now.
