### ISSUE TITLE
Could'nt Send

### ISSUE THREAD

**Issue by VasanthiR** [MicrosoftDocs/bot-docs#423]
I have created the bot channel, and trying to test chat and it is throwing error as could'nt send retry. but it is working in emulator

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: cf112c0a-0400-ede4-ab7c-ce10f86d6f30
* Version Independent ID: 5fa92c50-b8d1-460c-aa3c-f3f851c15da9
* Content: [Deploy your bot to Azure - Bot Service](https://docs.microsoft.com/en-us/azure/bot-service/bot-builder-howto-deploy-azure?view=azure-bot-service-4.0)
* Content Source: [articles/bot-builder-howto-deploy-azure.md](https://github.com/MicrosoftDocs/bot-docs/blob/live/articles/bot-builder-howto-deploy-azure.md)
* Product: **bot-framework**
* GitHub Login: @ivorb
* Microsoft Alias: **v-ivorb**

**Comment by CathyQian** [comment]
If you are following every steps in the article and doing things corrected, your bot should be working in both emulator and webchat. Sometimes it takes a while for the bot to be deployed in Azure, so you just need to wait for some time if webchat doesn't work.

**Comment by cobalt9077** [comment]
I'm having the same issue. The AppService seems to terminate immediately after launching. I'm using the Bot Builder Echo Bot V4. Runs perfectly in the Emulator but in Azure, the app service terminates

**Comment by mandardhikari** [comment]
You need to do following
1) Add the azure end point to your .bot file and add the MicrosoftAppId and MicrosoftPwd to your .bot file. 
2) Encrypt your bot with the bot secret.
3) Add the Bot secret and file to bot file in your app service's app setting while doing deployment

**Comment by Kaiqb** [comment]
@VasanthiR - and if you need additional help, see support options listed on this page: 
https://docs.microsoft.com/en-us/azure/bot-service/bot-service-resources-links-help?view=azure-bot-service-4.0

**Comment by Diro92** [comment]
I am using visual studio 2015 and it has web config instead of .bot file. 
I have already added that. 
It still doesn't work. 
Do I need to run the bot in visual to have response from it in azure web chat test?
